kind: pipeline
name: default

clone:
  depth: 1

steps:
  - name: test
    image: aeris22/ruby:2.6-alpine
    commands:
      - bundle install
      - rspec

  - name: notify
    image: drillster/drone-email
    settings:
      host:
        from_secret: smtp.host
      port:
        from_secret: smtp.port
      from:
        from_secret: smtp.from
      skip_verify: true
    when:
      status: [ changed, failure ]
      instance:
        exclude:
          - cloud.drone.io
